---
AWSTemplateFormatVersion: '2010-09-09'
Description: Handel-created resources for Zappa application

Resources:
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: {{serviceName}}
      Path: "/services/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
              - "lambda.amazonaws.com"
              - "events.amazonaws.com"
              - "apigateway.amazonaws.com"
            Action:
            - "sts:AssumeRole"
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: {{serviceName}}
      Roles:
      - !Ref Role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        {{#each policyStatements}}
        - Effect: {{Effect}}
          Action:
          {{#each Action}}
          - '{{{this}}}'
          {{/each}}
          Resource:
          {{#each Resource}}
          - '{{{this}}}'
          {{/each}}
        {{/each}}

Outputs:
  RoleArn:
    Description: The ARN of the role
    Value: !GetAtt Role.Arn